### ISSUE TITLE
[Crash] Since last Gecklib update

### ISSUE THREAD

**Issue by moninformateur** [Dariensg/Hellions-Sniffer-Plus#11]
This error stop happening if I disable Sniffer Plus.

```
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Registry Object not present: snifferplus:stone_pine_leaves
```

Here the link to the [mclo.gs](https://mclo.gs/DkkfcHt)

**Comment by Dariensg** [comment]
Please supply the full log, not just the crash report. The true error is being hidden
