### ISSUE TITLE
Crash on World Load 1.20.1

### ISSUE THREAD

**Issue by Zelioth** [Dariensg/Hellions-Sniffer-Plus#12]
Minecraft 1.20.1
Forge 47.1.3
Sniffer+ 0.2.0

Looks like some sort of issue with the way the biome is being generated on world load. I am using 47.1.3 Forge because tons of mods removed support for later versions. I look forward to using this mod since you've put such hard work into it. I would like to include it in our mod pack "Friends United" if we can get this crash fixed 👯 

Removing the mod removed the crash and allows everything to load properly. 

LOG 
https://gist.github.com/Zelioth/8f9431620c6b65cf7fb5358eb3997a77

Debug
https://gist.github.com/Zelioth/9b8fc836dbbc123680337300c5e7bf14

Crash
https://gist.github.com/Zelioth/07e2e1ecca6e3b0ebe84d27efbdfaa88

**Comment by NobodyH3re** [comment]
I'm having a similar issue, it seems that its something about the stone pine log for me at least
