### ISSUE TITLE
random crash pls help

### ISSUE THREAD

**Issue by jojofenin99** [Dariensg/Hellions-Sniffer-Plus#15]
here is the crash and normal log
[crash-2023-09-20_19.46.50-client.txt](https://github.com/Dariensg/Hellions-Sniffer-Plus/files/12706582/crash-2023-09-20_19.46.50-client.txt)
[latest.log](https://github.com/Dariensg/Hellions-Sniffer-Plus/files/12706583/latest.log)

**Comment by Dariensg** [comment]
The crash report has a falsely identified issue. The real issues are in the latest.log and none of them have to do with this mod.
