### ISSUE TITLE
Timeless Grotto replaces Lush Caves

### ISSUE THREAD

**Issue by spencerfrost** [Dariensg/Hellions-Sniffer-Plus#16]
Just added this mod to my world and reset all unused chunks so that the Timeless Grotto would generate only to find that nearly every lush cave in my world has been REPLACED by the Timeless Grotto. This is VERY unexpected behaviour and has upset a bunch of players who are wondering where we will get more spore blossoms from. It would be great if the Timeless Grotto would either be available as a config option or if it just simply didn't replace lush caves.

**Comment by Dariensg** [comment]
It doesn't replace Lush Caves. The way the biome system works, it should generate near Lush Caves, but it's not outright replacing them. It just means that the noise maps at that part of the world were closer to the parameters for the Timeless Grotto than Lush Caves.
