### ISSUE TITLE
Curseforge keeps downloading the wrong version of this mod.

### ISSUE THREAD

**Issue by WilliamBlaze** [Dariensg/Hellions-Sniffer-Plus#2]
Due to the bug fix update file carrying the same name as the bugged file - [Hellion's Sniffer+ Forge 0.2.0] , the Cursgeforge application can't tell the difference between the two files, causing the curseforge app to choose the older file of the two and automatically download it to users in place of the newly intended update.

A minor file Name change adjustment to the uploaded file is required to correct this.

So instead of "Hellion's Sniffer+ Forge 0.2.0" - it will need to be changed to "Hellion's Sniffer+ Forge 0.2.1" for example so the forge app will recognize the difference between the uploaded files and allow users to choose the newer file within the curseforge app.

I actually went onto the legacy curseforge site page for the mod to access and manually downloaded the updated file into the instance I'm using the mod in just to get the fixed version in my mod folder to confirm if this was the case and rule out if the update was busted too.

Your update functions as intended, no more world crashing on load up, so then that means the app is just repeatedly shoving the bugged file onto users in place of the updated version because the Curseforge app can't tell the difference between the two "[Hellion's Sniffer+ Forge 0.2.0]" files due to both sharing the same name.

**Comment by Dariensg** [comment]
I'm not sure what you mean. There is only one Sniffer+ Forge 0.2.0 version. I've just double checked the page to make sure, but I'm only seeing one still. Could you link me to both of these versions so I can take a look what you're seeing?

**Comment by WilliamBlaze** [comment]
the correct version for forge wasn't downloading correctly from the curseforge app on my end, after double checking the files it seems the automatic downloader was sticking me with the FABRIC version at the time - the issue seems corrected though, and i can't even recreate it now so it was probably just a one off bug between the website and Overwolf's Curseforge app itself. i think we can close this one.
