### ISSUE TITLE
crash on modpack loading 1.20.1 forge 47.2.0

### ISSUE THREAD

**Issue by Thunderrock424242** [Dariensg/Hellions-Sniffer-Plus#20]
[debug.log](https://github.com/Dariensg/Hellions-Sniffer-Plus/files/13269855/debug.log)
[latest.log](https://github.com/Dariensg/Hellions-Sniffer-Plus/files/13269857/latest.log)

**Comment by Dariensg** [comment]
Definitely not Sniffer+, so not too sure why you're reporting it here. The only mentions of Sniffer+ in either of those logs is saying that it's installed and functioning, whereas there are 30 other errors from other mods as pointed out in your latest.log.

**Comment by Thunderrock424242** [comment]
> Definitely not Sniffer+, so not too sure why you're reporting it here. The only mentions of Sniffer+ in either of those logs is saying that it's installed and functioning, whereas there are 30 other errors from other mods as pointed out in your latest.log.

When it crashed the mc crash report said this ![image](https://github.com/Dariensg/Hellions-Sniffer-Plus/assets/119463825/51cb1e13-7d5c-401f-ba8c-f915e02ae5a2)

**Comment by Dariensg** [comment]
That's a false error that happens because the Forge registries shut down when a mod crashes on startup. The logs contain the actual errors. Like I said, there's 30 of them and none are this mod.

**Comment by Thunderrock424242** [comment]
Ok
