### ISSUE TITLE
Crash on modpack loading

### ISSUE THREAD

**Issue by Thunderrock424242** [Dariensg/Hellions-Sniffer-Plus#21]
![image](https://github.com/Dariensg/Hellions-Sniffer-Plus/assets/119463825/662bfe4f-e821-4f5b-948b-d6a1caa5cb4a)

**Comment by Poopooracoocoo** [comment]
Please share the crash report and log. The "view crash report" will show it to you.

**Comment by katubug** [comment]
[crash-2024-01-03_13.42.48-client.txt](https://github.com/Dariensg/Hellions-Sniffer-Plus/files/13836474/crash-2024-01-03_13.42.48-client.txt)

I don't have the log, but I do have this same crash report!

**Comment by Dariensg** [comment]
Crash report is irrelevant on this. It's not a Sniffer+ issue. The log would show the real issue.

**Comment by Thunderrock424242** [comment]
> Crash report is irrelevant on this. It's not a Sniffer+ issue. The log would show the real issue.

Why does your mod always appear in a crash report even tho your mod did not cause it is there a way you can fix that?

**Comment by Dariensg** [comment]
It's because Forge doesn't abort startup when a mod fails to load, but freezes registries. So none of the blocks register, but it still attempts to load the game. Resulting in my mod erroring since it expects things to be registered, but it doesn't when another mod breaks.
