### ISSUE TITLE
Crash on modpack load - BlockColorProviders

### ISSUE THREAD

**Issue by katubug** [Dariensg/Hellions-Sniffer-Plus#25]
I just got this crash on load with Sniffer Plus 0.2.0 on Forge 47.2.18

[crash-2024-01-04_17.54.29-client.txt](https://github.com/Dariensg/Hellions-Sniffer-Plus/files/13836483/crash-2024-01-04_17.54.29-client.txt)

[latest.log](https://github.com/Dariensg/Hellions-Sniffer-Plus/files/13836486/latest.log)

**Comment by Dariensg** [comment]
Not a Sniffer+ issue. You're missing the dependency "Terrablender" for like 4 different mods.

**Comment by katubug** [comment]
Not missing but yeah, their latest update was being read as the wrong
version. Sorry, I reported before testing without the Sniffer+ mod, that's
my bad. As soon as it crashes with Sniffer+ disabled I realized my mistake.
Sorry!
