### ISSUE TITLE
stone_pine_trees issue crashing on client boot up

### ISSUE THREAD

**Issue by WindEssence** [Dariensg/Hellions-Sniffer-Plus#26]
[crash-2024-02-08_23.47.00-client.txt](https://github.com/Dariensg/Hellions-Sniffer-Plus/files/14224693/crash-2024-02-08_23.47.00-client.txt)

**Comment by WindEssence** [comment]
[latest.log](https://github.com/Dariensg/Hellions-Sniffer-Plus/files/14225729/latest.log)

**Comment by Dariensg** [comment]
Neither of the supplied logs indicate anything relevant to Sniffer+. The first crash report shows that BCLib is crashing and the second log shows that Create is crashing.
