### ISSUE TITLE
Mod Not able to load

### ISSUE THREAD

**Issue by m0thknight** [Dariensg/Hellions-Sniffer-Plus#27]
[crash-2024-02-22_12.29.28-client.txt](https://github.com/Dariensg/Hellions-Sniffer-Plus/files/14379082/crash-2024-02-22_12.29.28-client.txt)

**Comment by Dariensg** [comment]
This error is not actually caused by Sniffer+, but by other mods crashing during startup. Check your logs (not crash reports) for the true error.
