### ISSUE TITLE
Crash on startup, stone_pine_leaves

### ISSUE THREAD

**Issue by tallubhai** [Dariensg/Hellions-Sniffer-Plus#28]
Error: java.lang.NullPointerException: Registry Object not present: snifferplus:stone_pine_leaves

Game crashes on startup with above error message.

crash logs from 2 separate crashes with the same error message:

[crash-2024-03-02_18.54.59-client.txt](https://github.com/Dariensg/Hellions-Sniffer-Plus/files/14471528/crash-2024-03-02_18.54.59-client.txt)
[crash-2024-03-02_18.57.12-client.txt](https://github.com/Dariensg/Hellions-Sniffer-Plus/files/14471529/crash-2024-03-02_18.57.12-client.txt)

**Comment by Dariensg** [comment]
This error is not actually caused by Sniffer+, but by other mods crashing during startup. Check your logs (not crash reports) for the true error.

**Comment by tallubhai** [comment]
After further testing, it seems that Blueprint is responsible for the crash. For whatever reason the crash log incorrectly identified sniffer+.
