### ISSUE TITLE
Crash on game load

### ISSUE THREAD

**Issue by m0thknight** [Dariensg/Hellions-Sniffer-Plus#29]
[crash-2024-03-05_16.55.10-client.txt](https://github.com/Dariensg/Hellions-Sniffer-Plus/files/14503164/crash-2024-03-05_16.55.10-client.txt)

**Comment by Dariensg** [comment]
This isn't actually caused by Sniffer+. The crash report has a red herring error. The true error is in your log (not crash report). It's some other mod crashing on startup.
