### ISSUE TITLE
java.lang.NullPointerException: Registry Object not present: snifferplus:stone_pine_leaves

### ISSUE THREAD

**Issue by FullMetalMaster** [Dariensg/Hellions-Sniffer-Plus#3]
[crash-2023-07-05_17.12.51-client.txt](https://github.com/Dariensg/Hellions-Sniffer-Plus/files/11962154/crash-2023-07-05_17.12.51-client.txt)

**Comment by Dariensg** [comment]
Please provide the full log, not just the crash report. This occurs when another mod breaks during startup and is not caused by Sniffer+. To point you to which mod it is, I'll need a full log
