### ISSUE TITLE
Forced increased step height

### ISSUE THREAD

**Issue by SooarynAC** [Dariensg/Hellions-Sniffer-Plus#35]
With your mod on latest forge version there is increased step height, which can't be disabled. It is possible to walk up full blocks.

**Comment by Dariensg** [comment]
What MC and Mod version are you on?

**Comment by SooarynAC** [comment]
Minecraft 1.20.1, latest mod version available

**Comment by Dariensg** [comment]
Ah, yes. This is fixed on the 0.3.0 update for 1.20.4. I may try to backport it to 1.20.1 this weekend if I have time.

**Comment by SooarynAC** [comment]
Oh, okay, thanks ^^
Don't worry about it if you can't backport it

**Comment by sugan-reden** [comment]
Hi, I was about to write up a new issue about this when I saw there was already one open.

I am currently making a mega-pack with 748 mods and more to be added on MC 1.20.1, Forge 47.2.23 with mod 0.2.0. When testing, I found the step-assist was on no matter what I did in the options or in different mod configs. Was eventually able to narrow it down kind of by chance by stumbling on a reddit post that mentioned this mod. Sure enough, disabling the mod fixed the issue.

I really like your mod, and I would be disheartened to not be able to include it in the pack. Thus I am inclined to make a request and bump this issue.

**Comment by Dariensg** [comment]
Sounds good. I've heard enough interest in 1.20.1 since I've made the update, so I'll go back this weekend and backport the fixes to 1.20.1. I don't know how up to date I'll keep 1.20.1 in the future, but I don't want to leave it with bugs, so I'll at least do this! I'll try to get it done within about 24 hours from now.

**Comment by sugan-reden** [comment]
That's great to hear and also quite reasonable. Thank you very much for your swift reply and dedication. It is always refreshing to see. 😄

**Comment by Dariensg** [comment]
New version just put up on Modrinth and CurseForge for 1.20.1 that is identical to the 1.20.4 latest version in fixes! CurseForge may take a bit to approve, but Modrinth should already be up.

**Comment by sugan-reden** [comment]
Thank you very much, kind human :)
