### ISSUE TITLE
Stone Pine crash? Posting this here since the issue seems resumed even after fixing a missing mod dependency.

### ISSUE THREAD

**Issue by dalekfan** [Dariensg/Hellions-Sniffer-Plus#7]
Something appears to be wrong with the stone pine.

[crash-2023-07-27_22.54.21-client.txt](https://github.com/Dariensg/Hellions-Sniffer-Plus/files/12189734/crash-2023-07-27_22.54.21-client.txt)
[latest.log](https://github.com/Dariensg/Hellions-Sniffer-Plus/files/12189735/latest.log)

**Comment by Dariensg** [comment]
As the supplied log shows, this is an error with Macaw's Bridges BOP, not Sniffer+.
