### ISSUE TITLE
Sign crashes me.

### ISSUE THREAD

**Issue by evelynn999000** [Dariensg/Hellions-Sniffer-Plus#8]
[crash-2023-07-31_06.25.19-client.txt](https://github.com/Dariensg/Hellions-Sniffer-Plus/files/12214167/crash-2023-07-31_06.25.19-client.txt)

Crashed when placing sign.

**Comment by FuturisticDruid** [comment]
Noticed 2 things in recent log-

Unable to load model: 'snifferplus:potted_stone_pine_sapling#inventory' referenced from: snifferplus:potted_stone_pine_sapling#inventory: java.io.FileNotFoundException: snifferplus:models/item/potted_stone_pine_sapling.json
and
"Failed to generate hanging sign extension texture for snifferplus:stone_pine. Could be that the target mod isnt registering their wood type properly"

**Comment by Zunwolf1896** [comment]
We figured out having the Epic Knights mod isntalled was causing these crashes, I have linked the bugs together.

**Comment by Dariensg** [comment]
Given that any of the other mods causes Epic Knights to crash, I'm assuming this is something they have to fix, but I'll leave this issue open for now just in case.
