### ISSUE TITLE
Stone Pine Crash

### ISSUE THREAD

**Issue by SantiiMari** [Dariensg/Hellions-Sniffer-Plus#9]
Crash Report:
https://mclo.gs/p3MXgMe

Latest Log:

![crash sniffer +](https://github.com/Dariensg/Hellions-Sniffer-Plus/assets/44756162/ebb180cc-1a36-4791-9343-5e18f0c60ae9)

**Comment by Dariensg** [comment]
This is not actually caused by Sniffer+. Some other mod is crashing your game. Please supply the log, not crash report, and I can point you to what mod is the problem

**Comment by SantiiMari** [comment]
I See, in that case, my apologies for creating this issue under your mod!

This is from latest log : https://mclo.gs/yo3h9i4

**Comment by Dariensg** [comment]
You're all good! It's a common issue here. In the next version I'm gonna try and see if I can make this not happen. According to that log, the error seems to come from Patchouli. I'd double check you have the right version. That said, the event Patchouli is looking for should exist in 1.20.1 I'd think, so not sure why it's erroring.
